### ISSUE TITLE
Time coordinate values are incorrect in resampled extractions

### ISSUE THREAD

**Issue by douglatornell** [UBC-MOAD/Reshapr#102]
Example extraction config:
```yaml
# Reshapr configuration to extract month-averages of interesting chemistry variables                                                                                                                                                                                                 
# near Iona Island wastewater outfall                                                                                                                                                                                                                                            

dataset:
  model profile: /ocean/jtao/MOAD/analysis-jake/notebooks/wastewater/model_profiles/SalishSeaCast-202111-wastewater-salish.yaml
  time base: day
  variables group: chemistry

dask cluster: salish_cluster.yaml

start date: 2018-01-01
end date: 2018-11-30
extract variables:
  - CO2_flux

resample:
  time interval: 1M
  aggregation: mean

extracted dataset:
  name: SalishSeaCast_wastewater_month_CO2_flux
  description: Month-averaged CO2 flux extracted from SalishSeaCast v202111
               NEMO model with wastewater outfalls
  dest dir: /ocean/dlatorne/MOAD/extractions/
```
Result (note time coordinate values at the end of output below):
```
ncdump -cst -v time SalishSeaCast_wastewater_month_CO2_flux_20180101_20181030.nc 
netcdf SalishSeaCast_wastewater_month_CO2_flux_20180101_20181030 {
dimensions:
	time = UNLIMITED ; // (10 currently)
	gridY = 898 ;
	gridX = 398 ;
variables:
	float CO2_flux(time, gridY, gridX) ;
		CO2_flux:_FillValue = NaNf ;
		CO2_flux:standard_name = "surface_downward_mole_flux_of_carbon_dioxide" ;
		CO2_flux:long_name = "Flux of CO2 from Atmosphere to Ocean" ;
		CO2_flux:units = "mmol m-2 s-1" ;
		CO2_flux:_Storage = "chunked" ;
		CO2_flux:_ChunkSizes = 1, 898, 398 ;
		CO2_flux:_Shuffle = "true" ;
		CO2_flux:_DeflateLevel = 4 ;
		CO2_flux:_Endianness = "little" ;
	int64 gridY(gridY) ;
		gridY:standard_name = "y" ;
		gridY:long_name = "Grid Y" ;
		gridY:units = "count" ;
		gridY:comment = "gridY values are grid indices in the model y-direction" ;
		gridY:_Storage = "chunked" ;
		gridY:_ChunkSizes = 898 ;
		gridY:_Shuffle = "true" ;
		gridY:_DeflateLevel = 4 ;
		gridY:_Endianness = "little" ;
	int64 gridX(gridX) ;
		gridX:long_name = "Grid X" ;
		gridX:standard_name = "x" ;
		gridX:comment = "gridX values are grid indices in the model x-direction" ;
		gridX:units = "count" ;
		gridX:_Storage = "chunked" ;
		gridX:_ChunkSizes = 398 ;
		gridX:_Shuffle = "true" ;
		gridX:_DeflateLevel = 4 ;
		gridX:_Endianness = "little" ;
	float time(time) ;
		time:long_name = "Time Axis" ;
		time:calendar = "proleptic_gregorian" ;
		time:standard_name = "time" ;
		time:comment = "time values are UTC at the centre of the intervals over which the calculated model results are averaged; e.g. the field average values for January 2022 have a time value of 2022-01-15 12:00:00Z, and those for April 2022 have a time value of 2022-04-15 00:00:00Z" ;
		time:units = "days since 2007-01-01T12:00:00" ;
		time:time_origin = "2007-01-01 12:00:00" ;
		time:_Storage = "chunked" ;
		time:_ChunkSizes = 1 ;
		time:_Shuffle = "true" ;
		time:_DeflateLevel = 4 ;
		time:_Endianness = "little" ;

// global attributes:
		:name = "SalishSeaCast_wastewater_month_CO2_flux_20180101_20181030" ;
		:description = "Month-averaged CO2 flux extracted from SalishSeaCast v202111 NEMO model with wastewater outfalls" ;
		:history = "2023-11-01 10:01 -07:00: Generated by `reshapr extract /ocean/dlatorne/MOAD/extractions/../extract_co2.yaml`" ;
		:Conventions = "CF-1.6" ;
		:_NCProperties = "version=2,netcdf=4.9.2,hdf5=1.14.2" ;
		:_SuperblockVersion = 2 ;
		:_IsNetcdf4 = 1 ;
		:_Format = "netCDF-4" ;
data:

 time = "2018-05-31 12", "2018-07-01 12", "2018-07-29 12", "2018-08-29 12", 
    "2018-09-28 12", "2018-10-29 12", "2018-11-28 12", "2018-12-29 12", 
    "2019-01-29 12", "2019-02-28 12" ;
}
```
