### ISSUE TITLE
Improve extract sub-command selection semantics

### ISSUE THREAD

**Issue by douglatornell** [UBC-MOAD/Reshapr#38]
Becca requested an extraction of variables at 2 depths (z=2 and z=28) at a single grid point (y=450, x=270). The `selection` stanza that is presently required to accomplish that is:
```yaml
selection:
  depth:
    depth min: 2
    depth max: 29
    depth interval: 26
  grid y:
    y min: 450
    y max: 451
  grid x:
    x min: 270
    x max: 271
```
It would be more intuitive if that stanza were:
```yaml
selection:
  depth:
    depth min: 2
    depth max: 28
    depth interval: 26
  grid y:
    y min: 450
    y max: 450
  grid x:
    x min: 270
    x max: 270
```
That should be doable by adding 1 to the `* max* values in the code instead of forcing the user to do it in the config.
