### ISSUE TITLE
Unrequested variable in extractions that span date of variable added to dataset

### ISSUE THREAD

**Issue by douglatornell** [UBC-MOAD/Reshapr#51]
Discovered during investigation of issue #43.

When an extraction date range includes the date on which a variable was added to a dataset, the added variable is included in the extracted dataset regardless of whether or not it is in the list of requested variables. Known occurrences of this are:

* `HRDPS-2.5km-operational.yaml` profile for `percentcloud` variable added to dataset on 8-Jul-2017
* `HRDPS-2.5km-operational.yaml` profile for variables `LHTFL_surface`, `PRATE_surface`, and `RH_2maboveground` added to dataset on 6-Dec-2018

This issue is demonstrated for the 1st of those cases by the extraction config:
```yaml
dataset:
  model profile: HRDPS-2.5km-operational.yaml
  time base: hour
  variables group: surface fields

dask cluster: salish_cluster.yaml

start date: 2017-07-01
end date: 2017-07-31

extract variables:
  - precip

extracted dataset:
  name: HRDPS_hour_precip_surface
  description: Hour-averaged surface precip rate extracted from HRDPS 2.5km operational product
  dest dir: /tmp/
```
The extracted dataset contains variables `precip` as requested, and `percentcloud`, with the latter having `NaN` values prior to 2017-07-08.
